# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 23:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of', models.PositiveIntegerField(verbose_name='Numer lekcji')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktywny')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Lekcja',
                'verbose_name_plural': 'Lekcje',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LessonTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('short_description', models.TextField(max_length=250, verbose_name='Opis')),
                ('slug', models.SlugField(verbose_name='Adres url')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Tre\u015b\u0107')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.Lesson')),
            ],
            options={
                'managed': True,
                'db_table': 'lessons_lesson_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'Lekcja Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lessontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
