# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses', verbose_name='Zdj\u0119cie'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Zdj\u0119cie'),
        ),
    ]
