# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 02:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170203_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetranslation',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Opis'),
        ),
    ]
